backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 8;
shadow-opacity = 0.22;

fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 5;

corner-radius = 10;

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
